device: 192.168.5.160:6666
interval: 0.3
threshold: 0.85
adb_path: adb
screenshot_dir: screenshots
scrcpy:
  enabled: true
  path: scrcpy
  max_size: 800
tasks:
- name: 帮助
  enabled: true
  template: templates/help_new.png
  action: tap
  offset_x: 0
  offset_y: 0
  cooldown: 0.3
  max_triggers: 0
- name: 关闭聊天
  enabled: true
  template: templates/close_chat.png
  action: tap
  offset_x: -120
  offset_y: 0
  cooldown: 0.3
  max_triggers: 0
chains:
- name: 治疗
  enabled: true
  reset_timeout: 10
  steps:
  - template: templates/1.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/2.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/3.png
    action: tap
    cooldown: 0.1
  - action: tap_coord
    x: 700
    y: 400
    cooldown: 0.1
- name: 打巨兽
  enabled: true
  reset_timeout: 10
  skip_conditions:
  - monitor: 队列检测
    field: value
    op: <
    value: 1
  - monitor: 体力检测
    field: current
    op: <
    value: 25
  steps:
  - action: tap
    cooldown: 0.3
    threshold: 0.85
    template: C:/Users/fikiy/WorkBuddy/android-bot/templates/crop_032840_1192_2968_1400_3206.png
    x: 0
    y: 0
    offset_x: 0
    offset_y: 0
    keycode: 4
    skippable: true
  - template: templates/2-1.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/2-2.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/2-3.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/2-4.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/2-5.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  - template: templates/2-6.png
    action: tap
    cooldown: 0.1
    threshold: 0.65
  close_template: templates/x.png
monitors:
- name: 队列检测
  enabled: true
  region:
  - 401
  - 511
  - 484
  - 597
  report: remaining
  interval: 5
  alert_threshold: 0
  pre_type: template
  pre_template: templates/crop_035239_1183_2946_1417_3211.png
  pre_skippable: false
  fixed_total: 0
  close_template: ''
- name: 体力检测
  enabled: true
  pre_tap:
  - 92
  - 186
  region:
  - 228
  - 2862
  - 384
  - 2916
  fixed_total: 200
  report: current
  interval: 60
  alert_threshold: 25
  close_template: templates/close.png
  pre_type: tap
